services:
  app-a:
    extends:
      file: docker-compose-app.yaml
      service: app
    depends_on:
    - db-a  
  db-a:
    extends:
      file: docker-compose-db.yaml
      service: postgres
  pgadmin-a:
    extends:
      file: docker-compose-pgadmin.yaml
      service: pgadmin-compose
    depends_on:
    - db-a                      