name: Deploy winov

on:
  workflow_call:

jobs:
    deploy_copy:
        runs-on: ubuntu-latest
    
        steps:
        - uses: actions/checkout@v4 

        - name: ssh deploy
          uses: easingthemes/ssh-deploy@main
          with:
            SSH_PRIVATE_KEY: ${{ secrets.REMOTE_WINOV_PRIVATEKEY }}
            ARGS: "-rlgoDzvc -i --delete"
            REMOTE_PORT: ${{ secrets.REMOTE_WINOV_PORT }}
            REMOTE_HOST: ${{ secrets.REMOTE_WINOV_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_WINOV_USER }}
            TARGET: /home/${{ secrets.REMOTE_WINOV_USER }}/CI-01/
            EXCLUDE: "postgres-data"

        - name: executing remote ssh commands using password
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ secrets.REMOTE_WINOV_HOST }}
            username: ${{ secrets.REMOTE_WINOV_USER }}
            key: ${{ secrets.REMOTE_WINOV_PRIVATEKEY }}
            port: ${{ secrets.REMOTE_WINOV_PORT }}
            script: |
              export HOST=${{ secrets.REMOTE_WINOV_DBHOST }}
              export DBPORT=${{ secrets.REMOTE_WINOV_DBPORT }}
              export USER=${{ secrets.REMOTE_WINOV_DBUSER }}
              export DBNAME=${{ secrets.REMOTE_WINOV_DBNAME }}
              export PASSWORD=${{ secrets.REMOTE_WINOV_DBPASSWORD }}
              export PORT=8000  




                   